### ISSUE TITLE
Version 1.16.5, the engine causes the game to crash.

### ISSUE THREAD

**Issue by SSpinachZ** [CalenXwX/BuildCraft#8]
When I activate the engine with the redstone signal, the game crashes immediately. I removed all other mods keeping only BC and the result is still the same.

https://github.com/user-attachments/assets/4559b1bd-cefa-4175-95a3-afccdffd8990
[crash-2024-08-29_23.32.16-server.txt](https://github.com/user-attachments/files/16801632/crash-2024-08-29_23.32.16-server.txt)

**Comment by CalenXwX** [comment]
Fixed :)

commit ea40975cc4ace4f2b5717db7d4aa4da31622bd2d
